'use client'
import './globals.css'
import {motion, AnimatePresence} from 'framer-motion'
import { Poppins } from 'next/font/google'
import Header from './Components/Header'
import Navigation from './Components/Navigation'


const poppins = Poppins({weight:'400', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      
      <body className={`${poppins.className} overflow-x-hidden overflow-y-hidden`} >
        
        <Header/>
       <main className='bg-OxfordBlue h-screen'>
        <Navigation/>

        {children}
       </main>
        
        </body>
        
    </html>
    
  )
}
